
export const spacing = {
  1: {
    name: "01",
    type: "spacing",
    value: "2px",
    token: "--spacing-01",
  },
  2: {
    name: "02",
    type: "spacing",
    value: "4px",
    token: "--spacing-02",
  },
  3: {
    name: "03",
    type: "spacing",
    value: "6px",
    token: "--spacing-03",
  },
  4: {
    name: "04",
    type: "spacing",
    value: "8px",
    token: "--spacing-04",
  },
  5: {
    name: "05",
    type: "spacing",
    value: "12px",
    token: "--spacing-05",
  },
  6: {
    name: "06",
    type: "spacing",
    value: "16px",
    token: "--spacing-06",
  },
  7: {
    name: "07",
    type: "spacing",
    value: "20px",
    token: "--spacing-07",
  },
  8: {
    name: "08",
    type: "spacing",
    value: "24px",
    token: "--spacing-08",
  },
  9: {
    name: "09",
    type: "spacing",
    value: "28px",
    token: "--spacing-09",
  },
  10: {
    name: "10",
    type: "spacing",
    value: "32px",
    token: "--spacing-10",
  },
  11: {
    name: "11",
    type: "spacing",
    value: "36px",
    token: "--spacing-11",
  },
  12: {
    name: "12",
    type: "spacing",
    value: "40px",
    token: "--spacing-12",
  },
  13: {
    name: "13",
    type: "spacing",
    value: "44px",
    token: "--spacing-13",
  },
  14: {
    name: "14",
    type: "spacing",
    value: "48px",
    token: "--spacing-14",
  },
  15: {
    name: "15",
    type: "spacing",
    value: "52px",
    token: "--spacing-15",
  },
  16: {
    name: "16",
    type: "spacing",
    value: "56px",
    token: "--spacing-16",
  },
  17: {
    name: "17",
    type: "spacing",
    value: "60px",
    token: "--spacing-17",
  },
  18: {
    name: "18",
    type: "spacing",
    value: "64px",
    token: "--spacing-18",
  },
  19: {
    name: "19",
    type: "spacing",
    value: "68px",
    token: "--spacing-19",
  },
  20: {
    name: "20",
    type: "spacing",
    value: "72px",
    token: "--spacing-20",
  },
  21: {
    name: "21",
    type: "spacing",
    value: "76px",
    token: "--spacing-21",
  },
  22: {
    name: "22",
    type: "spacing",
    value: "80px",
    token: "--spacing-22",
  },
  23: {
    name: "23",
    type: "spacing",
    value: "84px",
    token: "--spacing-23",
  },
  24: {
    name: "24",
    type: "spacing",
    value: "88px",
    token: "--spacing-24",
  },
  25: {
    name: "25",
    type: "spacing",
    value: "92px",
    token: "--spacing-25",
  },
  26: {
    name: "26",
    type: "spacing",
    value: "96px",
    token: "--spacing-26",
  },
  27: {
    name: "27",
    type: "spacing",
    value: "100px",
    token: "--spacing-27",
  },
  28: {
    name: "28",
    type: "spacing",
    value: "104px",
    token: "--spacing-28",
  },
  29: {
    name: "29",
    type: "spacing",
    value: "108px",
    token: "--spacing-29",
  },
  30: {
    name: "30",
    type: "spacing",
    value: "112px",
    token: "--spacing-30",
  },
  31: {
    name: "31",
    type: "spacing",
    value: "116px",
    token: "--spacing-31",
  },
  32: {
    name: "32",
    type: "spacing",
    value: "120px",
    token: "--spacing-32",
  },
  33: {
    name: "33",
    type: "spacing",
    value: "124px",
    token: "--spacing-33",
  },
  34: {
    name: "34",
    type: "spacing",
    value: "128px",
    token: "--spacing-34",
  },
  35: {
    name: "35",
    type: "spacing",
    value: "132px",
    token: "--spacing-35",
  },
  36: {
    name: "36",
    type: "spacing",
    value: "136px",
    token: "--spacing-36",
  },
  37: {
    name: "37",
    type: "spacing",
    value: "140px",
    token: "--spacing-37",
  },
  38: {
    name: "38",
    type: "spacing",
    value: "144px",
    token: "--spacing-38",
  },
  39: {
    name: "39",
    type: "spacing",
    value: "148px",
    token: "--spacing-39",
  },
  40: {
    name: "40",
    type: "spacing",
    value: "152px",
    token: "--spacing-40",
  },
  41: {
    name: "41",
    type: "spacing",
    value: "156px",
    token: "--spacing-41",
  },
  42: {
    name: "42",
    type: "spacing",
    value: "160px",
    token: "--spacing-42",
  },
  43: {
    name: "43",
    type: "spacing",
    value: "164px",
    token: "--spacing-43",
  },
  44: {
    name: "44",
    type: "spacing",
    value: "168px",
    token: "--spacing-44",
  },
  45: {
    name: "45",
    type: "spacing",
    value: "172px",
    token: "--spacing-45",
  },
  46: {
    name: "46",
    type: "spacing",
    value: "176px",
    token: "--spacing-46",
  },
  47: {
    name: "47",
    type: "spacing",
    value: "180px",
    token: "--spacing-47",
  },
  48: {
    name: "48",
    type: "spacing",
    value: "184px",
    token: "--spacing-48",
  },
  49: {
    name: "49",
    type: "spacing",
    value: "188px",
    token: "--spacing-49",
  },
  50: {
    name: "50",
    type: "spacing",
    value: "192px",
    token: "--spacing-50",
  },
};
