export const fontFamily = {
  sansSerif: {
    name: "sansSerif",
    type: "fontFamily",
    value: "'Helvetica Neue', Arial, sans-serif",
    token: "--font-family-sans-serif",
  },
  serif: {
    name: "serif",
    type: "fontFamily",
    value: "Georgia, 'Times New Roman', serif",
    token: "--font-family-serif",
  },
  monospace: {
    name: "monospace",
    type: "fontFamily",
    value: "'Courier New', Courier, monospace",
    token: "--font-family-monospace",
  },
  cursive: {
    name: "cursive",
    type: "fontFamily",
    value: "'Comic Sans MS', cursive, sans-serif",
    token: "--font-family-cursive",
  },
  fantasy: {
    name: "fantasy",
    type: "fontFamily",
    value: "Impact, fantasy",
    token: "--font-family-fantasy",
  },
  systemUI: {
    name: "systemUI",
    type: "fontFamily",
    value: "system-ui, sans-serif",
    token: "--font-family-system-ui",
  },
  avenir: {
    name: "avenir",
    type: "fontFamily",
    value: "Avenir, sans-serif",
    token: "--font-family-avenir",
  },
  futura: {
    name: "futura",
    type: "fontFamily",
    value: "Futura, sans-serif",
    token: "--font-family-futura",
  },
  gillSans: {
    name: "gillSans",
    type: "fontFamily",
    value: "'Gill Sans', sans-serif",
    token: "--font-family-gill-sans",
  },
  roboto: {
    name: "roboto",
    type: "fontFamily",
    value: "Roboto, sans-serif",
    token: "--font-family-roboto",
  },
  openSans: {
    name: "openSans",
    type: "fontFamily",
    value: "'Open Sans', sans-serif",
    token: "--font-family-open-sans",
  },
  lato: {
    name: "lato",
    type: "fontFamily",
    value: "Lato, sans-serif",
    token: "--font-family-lato",
  },
  montserrat: {
    name: "montserrat",
    type: "fontFamily",
    value: "Montserrat, sans-serif",
    token: "--font-family-montserrat",
  },
  playfairDisplay: {
    name: "playfairDisplay",
    type: "fontFamily",
    value: "'Playfair Display', serif",
    token: "--font-family-playfair-display",
  },
  merriweather: {
    name: "merriweather",
    type: "fontFamily",
    value: "Merriweather, serif",
    token: "--font-family-merriweather",
  },
  arial: {
    name: "arial",
    type: "fontFamily",
    value: "Arial, sans-serif",
    token: "--font-family-arial",
  },
  timesNewRoman: {
    name: "timesNewRoman",
    type: "fontFamily",
    value: "'Times New Roman', serif",
    token: "--font-family-times-new-roman",
  },
};
