
export const fontHeight = {
  1: {
    name: "01",
    type: "fontHeight",
    value: "12px",
    token: "--font-height-01",
  },
  2: {
    name: "02",
    type: "fontHeight",
    value: "16px",
    token: "--font-height-02",
  },
  3: {
    name: "03",
    type: "fontHeight",
    value: "20px",
    token: "--font-height-03",
  },
  4: {
    name: "04",
    type: "fontHeight",
    value: "24px",
    token: "--font-height-04",
  },
  5: {
    name: "05",
    type: "fontHeight",
    value: "28px",
    token: "--font-height-05",
  },
  6: {
    name: "06",
    type: "fontHeight",
    value: "32px",
    token: "--font-height-06",
  },
  7: {
    name: "07",
    type: "fontHeight",
    value: "36px",
    token: "--font-height-07",
  },
  8: {
    name: "08",
    type: "fontHeight",
    value: "40px",
    token: "--font-height-08",
  },
  9: {
    name: "09",
    type: "fontHeight",
    value: "44px",
    token: "--font-height-09",
  },
  10: {
    name: "10",
    type: "fontHeight",
    value: "48px",
    token: "--font-height-10",
  },
  11: {
    name: "11",
    type: "fontHeight",
    value: "52px",
    token: "--font-height-11",
  },
  12: {
    name: "12",
    type: "fontHeight",
    value: "56px",
    token: "--font-height-12",
  },
  13: {
    name: "13",
    type: "fontHeight",
    value: "60px",
    token: "--font-height-13",
  },
  14: {
    name: "14",
    type: "fontHeight",
    value: "64px",
    token: "--font-height-14",
  },
  15: {
    name: "15",
    type: "fontHeight",
    value: "68px",
    token: "--font-height-15",
  },
  16: {
    name: "16",
    type: "fontHeight",
    value: "72px",
    token: "--font-height-16",
  },
  17: {
    name: "17",
    type: "fontHeight",
    value: "76px",
    token: "--font-height-17",
  },
  18: {
    name: "18",
    type: "fontHeight",
    value: "80px",
    token: "--font-height-18",
  },
  19: {
    name: "19",
    type: "fontHeight",
    value: "84px",
    token: "--font-height-19",
  },
  20: {
    name: "20",
    type: "fontHeight",
    value: "88px",
    token: "--font-height-20",
  },
  21: {
    name: "21",
    type: "fontHeight",
    value: "92px",
    token: "--font-height-21",
  },
  22: {
    name: "22",
    type: "fontHeight",
    value: "96px",
    token: "--font-height-22",
  },
  23: {
    name: "23",
    type: "fontHeight",
    value: "100px",
    token: "--font-height-23",
  },
  24: {
    name: "24",
    type: "fontHeight",
    value: "104px",
    token: "--font-height-24",
  },
  25: {
    name: "25",
    type: "fontHeight",
    value: "108px",
    token: "--font-height-25",
  },
  26: {
    name: "26",
    type: "fontHeight",
    value: "112px",
    token: "--font-height-26",
  },
  27: {
    name: "27",
    type: "fontHeight",
    value: "116px",
    token: "--font-height-27",
  },
  28: {
    name: "28",
    type: "fontHeight",
    value: "120px",
    token: "--font-height-28",
  },
  29: {
    name: "29",
    type: "fontHeight",
    value: "124px",
    token: "--font-height-29",
  },
  30: {
    name: "30",
    type: "fontHeight",
    value: "128px",
    token: "--font-height-30",
  },
  31: {
    name: "31",
    type: "fontHeight",
    value: "132px",
    token: "--font-height-31",
  },
  32: {
    name: "32",
    type: "fontHeight",
    value: "136px",
    token: "--font-height-32",
  },
  33: {
    name: "33",
    type: "fontHeight",
    value: "140px",
    token: "--font-height-33",
  },
  34: {
    name: "34",
    type: "fontHeight",
    value: "144px",
    token: "--font-height-34",
  },
  35: {
    name: "35",
    type: "fontHeight",
    value: "148px",
    token: "--font-height-35",
  },
  36: {
    name: "36",
    type: "fontHeight",
    value: "152px",
    token: "--font-height-36",
  },
  37: {
    name: "37",
    type: "fontHeight",
    value: "156px",
    token: "--font-height-37",
  },
  38: {
    name: "38",
    type: "fontHeight",
    value: "160px",
    token: "--font-height-38",
  },
  39: {
    name: "39",
    type: "fontHeight",
    value: "164px",
    token: "--font-height-39",
  },
  40: {
    name: "40",
    type: "fontHeight",
    value: "168px",
    token: "--font-height-40",
  },
  41: {
    name: "41",
    type: "fontHeight",
    value: "172px",
    token: "--font-height-41",
  },
  42: {
    name: "42",
    type: "fontHeight",
    value: "176px",
    token: "--font-height-42",
  },
  43: {
    name: "43",
    type: "fontHeight",
    value: "180px",
    token: "--font-height-43",
  },
  44: {
    name: "44",
    type: "fontHeight",
    value: "184px",
    token: "--font-height-44",
  },
  45: {
    name: "45",
    type: "fontHeight",
    value: "188px",
    token: "--font-height-45",
  },
  46: {
    name: "46",
    type: "fontHeight",
    value: "192px",
    token: "--font-height-46",
  },
  47: {
    name: "47",
    type: "fontHeight",
    value: "196px",
    token: "--font-height-47",
  },
  48: {
    name: "48",
    type: "fontHeight",
    value: "200px",
    token: "--font-height-48",
  },
  49: {
    name: "49",
    type: "fontHeight",
    value: "204px",
    token: "--font-height-49",
  },
  50: {
    name: "50",
    type: "fontHeight",
    value: "208px",
    token: "--font-height-50",
  },
};
